# See https://redocly.com/docs/cli/configuration/ for more information.
apis:
  sample@v1: 
    root: openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: error

features.openapi: 
  showConsole: true
  layout: 'stacked'
  htmlTemplate: ./docs/index.html
  theme:
    breakpoints:
      small: 10rem
      medium: 40rem
      large: 85rem
    colors:
      primary:
        main: rgba(246, 20, 63, 1)
        light: rgba(246, 20, 63, 0.42)
      success:
        main: rgba(28, 184, 65, 1)
        light: "#81ec9a"
        dark: "#083312"
        contrastText: "#000"
      text:
        primary: rgba(0, 0, 0, 1)
        secondary: "#4d4d4d"
      http:
        get: rgba(0, 200, 219, 1)
        post: rgba(28, 184, 65, 1)
        put: rgba(255, 187, 0, 1)
        delete: rgba(254, 39, 35, 1)
    typography:
      fontSize: 16px
      fontFamily: Fira Sans, Roboto, sans-serif
      optimizeSpeed: true
      smoothing: antialiased
      headings:
        fontWeight: bold
        lineHeight: 1em
      code:
        fontWeight: '600'
        color: rgba(92, 62, 189, 1)
        wrap: true
      links:
        color: rgba(246, 20, 63, 1)
        visited: rgba(246, 20, 63, 1)
        hover: "#fa768f"
    sidebar:
      width: 300px
      textColor: "#fff"
      backgroundColor: '#2a3b4c'
      activeBgColor: '#fff'
      activeTextColor: '#4a89dc'
    rightPanel:
      backgroundColor: rgba(55, 53, 71, 1)
      textColor: "#ffffff"

      
  generateCodeSamples:
    languages:  # Array of language config objects; indicates in which languages to generate code samples.
      - lang: curl
      - lang: Node.js
      - lang: JavaScript
      - lang: PHP
      - lang: Python
