openapi: 3.0.1
info:
  x-logo:
    url: 'https://shiipdemo.azurewebsites.net/ce5464ed455495b51ba7330371f5a7dd.png'
    altText: 'Shiip logo'
  title: Shiip Customer
  version: v1
  description: |
   # Introduction

     The purpose of this document is to outline the guidelines and specifications required to Create Consignments in the Cubiic system via Integration services. 
     
     There are two methods presented in this spec with which a client can integrate with Cubiic, a REST based web service, and a CSV upload service.
     ## 1.1. Revision history
      - 2021-02-15
       - Added explicit examples of UOMs
       - Fixed some various typos
    - 2021-02-02
        - CreateConsignment payload updated with additional properties
    - 2021-01-14
       - GetEstimates endpoint path updated
    - 2020-12-30
        - Fixed a broken link
    - 2020-11-24
        - Deprecate old CSV format, added new CSV spec
    - 2020-10-10
        - Added connote tracking endpoint
    - 2020-10-09
        - Added Webhook tracking event service
    - 2020-10-08
        - Added carrierCode and serviceCode parameters to CreateConsignment spec
    - 2020-09-07
        - Deprecated Reference parameter
    - 2020-08-11
        - Added ReceiverReferences and SenderReferences parameters
        - Added GetEstimates spec and corresponding consignmentNo parameter to CreateConsignment
       when using an estimate
    - 2020-03-02
        - Added CSV upload service
    - 2019-07-04
        - Initial public API spec
    # Cubiic API web service
    ## 2.1. Overview
     - The Cubiic API web service is a RESTful web service that allows an authenticated client to submit consignment data, which is then accessible as either an "Incomplete"/ Draft or "Ready" consignment in Cubiic.
    ## 2.1.1. Features
     - Accepts a single consignment object per request and creates a draft consignment in Cubiic
     - Creates the consignment in the appropriate Cubiic tenancy based on authentication token
     - Can assign a default carrier to the consignment based on Location preferences in Cubiic
  
servers:
  - url: https://shiippublicdemo.azurewebsites.net
paths:
  
  /TokenByWmsCode:
    $ref: paths/TokenByWmsCode.yaml
 

  /Consignment/CreateConsignment:
    $ref: paths/Consignment_CreateConsignment.yaml
  /Consignment/ManifestByNo/{manifestNo}:
    $ref: paths/Consignment_ManifestByNo_{manifestNo}.yaml
  /Estimate/GetEstimates:
    $ref: paths/Estimate_GetEstimates.yaml
  /Location/CreateLocation:
    $ref: paths/Location_CreateLocation.yaml
components:
  securitySchemes:
    Bearer:
      type: apiKey
      description: >-
        JWT Authorization header using the Bearer scheme. Example:
        "Authorization: Bearer {token}"
      name: Authorization
      in: header
security:
  - Bearer: []
